import 'package:cip_website/config/app_urls.dart';
import 'package:cip_website/utils/http_handlers.dart';
import 'package:cip_website/utils/storage_service.dart';
import 'package:flutter/material.dart';

class UserPermisssions extends ChangeNotifier {
  bool canCreateTickets = false;
  bool canViewTickets = false;
  bool canManageTickets = false;
  bool canUpdateTickets = false;
  bool canDeleteTickets = false;
  bool canCreateChecklists = false;
  bool canViewChecklists = false;
  bool canManageChecklists = false;
  bool canUpdateChecklists = false;
  bool canDeleteChecklists = false;
  bool canViewWhitePage = false;
  bool canManageWhitePage = false;
  bool canCreateEmployees = false;
  bool canViewEmployees = false;
  bool canManageEmployees = false;
  bool canUpdateEmployees = false;
  bool canDeleteEmployees = false;
  bool canCreateDepartments = false;
  bool canViewDepartments = false;
  bool canManageDepartments = false;
  bool canUpdateDepartments = false;
  bool canDeleteDepartments = false;
  bool canCreateCompany = false;
  bool canViewCompany = false;
  bool canManageCompany = false;
  bool canUpdateCompany = false;
  bool canDeleteCompany = false;
  bool canCreateDesignation = false;
  bool canViewDesignation = false;
  bool canManageDesignation = false;
  bool canUpdateDesignation = false;
  bool canDeleteDesignation = false;
  bool canCreateShift = false;
  bool canViewShift = false;
  bool canManageShift = false;
  bool canUpdateShift = false;
  bool canDeleteShift = false;
  bool canCreateRoles = false;
  bool canViewRoles = false;
  bool canManageRoles = false;
  bool canUpdateRoles = false;
  bool canDeleteRoles = false;
  bool canViewItTickets = false;
  bool canManageItTickets = false;
  bool canViewHrTickets = false;
  bool canManageHrTickets = false;
  bool canViewAdminTickets = false;
  bool canManageAdminTickets = false;
  bool canViewAllTickets = false;
  bool canManageAllTickets = false;
  bool canCreateNotifications = false;
  bool canViewNotifications = false;
  bool canManageNotifications = false;
  bool canUpdateNotifications = false;
  bool canDeleteNotifications = false;
  bool canCreateManagers = false;
  bool canViewManagers = false;
  bool canManageManagers = false;
  bool canUpdateManagers = false;
  bool canDeleteManagers = false;
  bool canCreateDefaultTickets = false;
  bool canViewDefaultTickets = false;
  bool canManageDefaultTickets = false;
  bool canUpdateDefaultTickets = false;
  bool canDeleteDefaultTickets = false;
  bool canCreateLeaveRequests = false;
  bool canViewLeaveRequests = false;
  bool canManageLeaveRequests = false;
  bool canUpdateLeaveRequests = false;
  bool canDeleteLeaveRequests = false;

Future<String?> getToken() async {
  var token = await storageService.readSecureStorage("ecos-user-token");
  return token;
}
  getAndSetRoles() async {
    var token = await getToken();
    var resp = await postRequesthandler(
      url: "${AppUrls.apiBaseUrl}/auth/permissions",
      token: token,
    );
    if (resp != null && resp.data != null) {
      canCreateTickets = resp.data["canCreateTickets"];
      canViewTickets = resp.data["canViewTickets"];
      canManageTickets = resp.data["canManageTickets"];
      canUpdateTickets = resp.data["canUpdateTickets"];
      canDeleteTickets = resp.data["canDeleteTickets"];
      canCreateChecklists = resp.data["canCreateChecklists"];
      canViewChecklists = resp.data["canViewChecklists"];
      canManageChecklists = resp.data["canManageChecklists"];
      canUpdateChecklists = resp.data["canUpdateChecklists"];
      canDeleteChecklists = resp.data["canDeleteChecklists"];
      canViewWhitePage = resp.data["canViewWhitePage"];
      canManageWhitePage = resp.data["canManageWhitePage"];
      canCreateEmployees = resp.data["canCreateEmployees"];
      canViewEmployees = resp.data["canViewEmployees"];
      canManageEmployees = resp.data["canManageEmployees"];
      canUpdateEmployees = resp.data["canUpdateEmployees"];
      canDeleteEmployees = resp.data["canDeleteEmployees"];
      canCreateDepartments = resp.data["canCreateDepartments"];
      canViewDepartments = resp.data["canViewDepartments"];
      canManageDepartments = resp.data["canManageDepartments"];
      canUpdateDepartments = resp.data["canUpdateDepartments"];
      canDeleteDepartments = resp.data["canDeleteDepartments"];
      canCreateCompany = resp.data["canCreateCompany"];
      canViewCompany = resp.data["canViewCompany"];
      canManageCompany = resp.data["canManageCompany"];
      canUpdateCompany = resp.data["canUpdateCompany"];
      canDeleteCompany = resp.data["canDeleteCompany"];
      canCreateDesignation = resp.data["canCreateDesignation"];
      canViewDesignation = resp.data["canViewDesignation"];
      canManageDesignation = resp.data["canManageDesignation"];
      canUpdateDesignation = resp.data["canUpdateDesignation"];
      canDeleteDesignation = resp.data["canDeleteDesignation"];
      canCreateShift = resp.data["canCreateShift"];
      canViewShift = resp.data["canViewShift"];
      canManageShift = resp.data["canManageShift"];
      canUpdateShift = resp.data["canUpdateShift"];
      canDeleteShift = resp.data["canDeleteShift"];
      canCreateRoles = resp.data["canCreateRoles"];
      canViewRoles = resp.data["canViewRoles"];
      canManageRoles = resp.data["canManageRoles"];
      canUpdateRoles = resp.data["canUpdateRoles"];
      canDeleteRoles = resp.data["canDeleteRoles"];
      canViewItTickets = resp.data["canViewItTickets"];
      canManageItTickets = resp.data["canManageItTickets"];
      canViewHrTickets = resp.data["canViewHrTickets"];
      canManageHrTickets = resp.data["canManageHrTickets"];
      canViewAdminTickets = resp.data["canViewAdminTickets"];
      canManageAdminTickets = resp.data["canManageAdminTickets"];
      canViewAllTickets = resp.data["canViewAllTickets"];
      canManageAllTickets = resp.data["canManageAllTickets"];
      canCreateNotifications = resp.data["canCreateNotifications"];
      canViewNotifications = resp.data["canViewNotifications"];
      canManageNotifications = resp.data["canManageNotifications"];
      canUpdateNotifications = resp.data["canUpdateNotifications"];
      canDeleteNotifications = resp.data["canDeleteNotifications"];
      canCreateManagers = resp.data["canCreateManagers"];
      canViewManagers = resp.data["canViewManagers"];
      canManageManagers = resp.data["canManageManagers"];
      canUpdateManagers = resp.data["canUpdateManagers"];
      canDeleteManagers = resp.data["canDeleteManagers"];
      canCreateDefaultTickets = resp.data["canCreateDefaultTickets"];
      canViewDefaultTickets = resp.data["canViewDefaultTickets"];
      canManageDefaultTickets = resp.data["canManageDefaultTickets"];
      canUpdateDefaultTickets = resp.data["canUpdateDefaultTickets"];
      canDeleteDefaultTickets = resp.data["canDeleteDefaultTickets"];
      canCreateLeaveRequests = resp.data["canCreateLeaveRequests"];
      canViewLeaveRequests = resp.data["canViewLeaveRequests"];
      canManageLeaveRequests = resp.data["canManageLeaveRequests"];
      canUpdateLeaveRequests = resp.data["canUpdateLeaveRequests"];
      canDeleteLeaveRequests = resp.data["canDeleteLeaveRequests"];
    }
    notifyListeners();
  }

  setToDefault() {
    canCreateTickets = false;
    canViewTickets = false;
    canManageTickets = false;
    canUpdateTickets = false;
    canDeleteTickets = false;
    canCreateChecklists = false;
    canViewChecklists = false;
    canManageChecklists = false;
    canUpdateChecklists = false;
    canDeleteChecklists = false;
    canViewWhitePage = false;
    canManageWhitePage = false;
    canCreateEmployees = false;
    canViewEmployees = false;
    canManageEmployees = false;
    canUpdateEmployees = false;
    canDeleteEmployees = false;
    canCreateDepartments = false;
    canViewDepartments = false;
    canManageDepartments = false;
    canUpdateDepartments = false;
    canDeleteDepartments = false;
    canCreateCompany = false;
    canViewCompany = false;
    canManageCompany = false;
    canUpdateCompany = false;
    canDeleteCompany = false;
    canCreateDesignation = false;
    canViewDesignation = false;
    canManageDesignation = false;
    canUpdateDesignation = false;
    canDeleteDesignation = false;
    canCreateShift = false;
    canViewShift = false;
    canManageShift = false;
    canUpdateShift = false;
    canDeleteShift = false;
    canCreateRoles = false;
    canViewRoles = false;
    canManageRoles = false;
    canUpdateRoles = false;
    canDeleteRoles = false;
    canViewItTickets = false;
    canManageItTickets = false;
    canViewHrTickets = false;
    canManageHrTickets = false;
    canViewAdminTickets = false;
    canManageAdminTickets = false;
    canViewAllTickets = false;
    canManageAllTickets = false;
    canCreateNotifications = false;
    canViewNotifications = false;
    canManageNotifications = false;
    canUpdateNotifications = false;
    canDeleteNotifications = false;
    canCreateManagers = false;
    canViewManagers = false;
    canManageManagers = false;
    canUpdateManagers = false;
    canDeleteManagers = false;
    canCreateDefaultTickets = false;
    canViewDefaultTickets = false;
    canManageDefaultTickets = false;
    canUpdateDefaultTickets = false;
    canDeleteDefaultTickets = false;
    canCreateLeaveRequests = false;
    canViewLeaveRequests = false;
    canManageLeaveRequests = false;
    canUpdateLeaveRequests = false;
    canDeleteLeaveRequests = false;
  }
}

// http://192.168.10.62:8000/

// api/auth/login  (email + password fields)
